package phpgen

import "strings"

// phpReservedWords is a map of PHP reserved words in lowercase
// This map should not be modified after initialization
var phpReservedWords = map[string]bool{
	// from https://www.php.net/manual/en/reserved.other-reserved-words.php
	"int":      true,
	"float":    true,
	"bool":     true,
	"string":   true,
	"true":     true,
	"false":    true,
	"null":     true,
	"void":     true,
	"iterable": true,
	"object":   true,
	"mixed":    true,
	"never":    true,

	// from https://www.php.net/manual/en/reserved.classes.php
	// predefined classes
	"directory":              true,
	"stdclass":               true,
	"__php_incomplete_class": true,
	"exception":              true,
	"errorexception":         true,
	"php_user_filter":        true,
	"closure":                true,
	"generator":              true,
	"arithmeticerror":        true,
	"assertionerror":         true,
	"divisionbyzeroerror":    true,
	"error":                  true,
	"throwable":              true,
	"parseerror":             true,
	"typeerror":              true,
	"self":                   true,
	"parent":                 true,

	// from https://www.php.net/manual/en/reserved.keywords.php
	// php keywords
	"__halt_compiler": true,
	"abstract":        true,
	"and":             true,
	"array":           true,
	"as":              true,
	"break":           true,
	"callable":        true,
	"case":            true,
	"catch":           true,
	"class":           true,
	"clone":           true,
	"const":           true,
	"continue":        true,
	"declare":         true,
	"default":         true,
	"die":             true,
	"do":              true,
	"echo":            true,
	"else":            true,
	"elseif":          true,
	"empty":           true,
	"enddeclare":      true,
	"endfor":          true,
	"endforeach":      true,
	"endif":           true,
	"endswitch":       true,
	"endwhile":        true,
	"eval":            true,
	"exit":            true,
	"extends":         true,
	"final":           true,
	"finally":         true,
	"fn":              true,
	"for":             true,
	"foreach":         true,
	"function":        true,
	"global":          true,
	"goto":            true,
	"if":              true,
	"implements":      true,
	"include":         true,
	"include_once":    true,
	"instanceof":      true,
	"insteadof":       true,
	"interface":       true,
	"isset":           true,
	"list":            true,
	"match":           true,
	"namespace":       true,
	"new":             true,
	"or":              true,
	"print":           true,
	"private":         true,
	"protected":       true,
	"public":          true,
	"readonly":        true,
	"require":         true,
	"require_once":    true,
	"return":          true,
	"static":          true,
	"switch":          true,
	"throw":           true,
	"trait":           true,
	"try":             true,
	"unset":           true,
	"use":             true,
	"var":             true,
	"while":           true,
	"xor":             true,
	"yield":           true,
	"yield from":      true,

	// compile-time constants
	"__class__":     true,
	"__dir__":       true,
	"__file__":      true,
	"__function__":  true,
	"__line__":      true,
	"__method__":    true,
	"__property__":  true,
	"__namespace__": true,
	"__trait__":     true,
}

// GetSafeName returns a safe PHP keyword
func GetSafeName(name string) string {
	if _, ok := phpReservedWords[strings.ToLower(name)]; ok {
		return GetSafeName(name + "_")
	}
	return name
}
