// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: tests/protos/imports.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     *Timestamp             `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Balance       *Money                 `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Coordinates   *Coordinates           `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tests_protos_imports_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tests_protos_imports_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tests_protos_imports_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *User) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetBalance() *Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *User) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

var File_tests_protos_imports_proto protoreflect.FileDescriptor

const file_tests_protos_imports_proto_rawDesc = "" +
	"\n" +
	"\x1atests/protos/imports.proto\x12\ftest.imports\x1a\x19tests/protos/common.proto\"\xd7\x01\n" +
	"\x04User\x12.\n" +
	"\aaddress\x18\x01 \x01(\v2\x14.test.common.AddressR\aaddress\x125\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x16.test.common.TimestampR\tcreatedAt\x12,\n" +
	"\abalance\x18\x03 \x01(\v2\x12.test.common.MoneyR\abalance\x12:\n" +
	"\vcoordinates\x18\x04 \x01(\v2\x18.test.common.CoordinatesR\vcoordinatesB\x18Z\vtests/go/pb\xca\x02\bTests\\PBb\x06proto3"

var (
	file_tests_protos_imports_proto_rawDescOnce sync.Once
	file_tests_protos_imports_proto_rawDescData []byte
)

func file_tests_protos_imports_proto_rawDescGZIP() []byte {
	file_tests_protos_imports_proto_rawDescOnce.Do(func() {
		file_tests_protos_imports_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_protos_imports_proto_rawDesc), len(file_tests_protos_imports_proto_rawDesc)))
	})
	return file_tests_protos_imports_proto_rawDescData
}

var file_tests_protos_imports_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_protos_imports_proto_goTypes = []any{
	(*User)(nil),        // 0: test.imports.User
	(*Address)(nil),     // 1: test.common.Address
	(*Timestamp)(nil),   // 2: test.common.Timestamp
	(*Money)(nil),       // 3: test.common.Money
	(*Coordinates)(nil), // 4: test.common.Coordinates
}
var file_tests_protos_imports_proto_depIdxs = []int32{
	1, // 0: test.imports.User.address:type_name -> test.common.Address
	2, // 1: test.imports.User.created_at:type_name -> test.common.Timestamp
	3, // 2: test.imports.User.balance:type_name -> test.common.Money
	4, // 3: test.imports.User.coordinates:type_name -> test.common.Coordinates
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tests_protos_imports_proto_init() }
func file_tests_protos_imports_proto_init() {
	if File_tests_protos_imports_proto != nil {
		return
	}
	file_tests_protos_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_protos_imports_proto_rawDesc), len(file_tests_protos_imports_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_protos_imports_proto_goTypes,
		DependencyIndexes: file_tests_protos_imports_proto_depIdxs,
		MessageInfos:      file_tests_protos_imports_proto_msgTypes,
	}.Build()
	File_tests_protos_imports_proto = out.File
	file_tests_protos_imports_proto_goTypes = nil
	file_tests_protos_imports_proto_depIdxs = nil
}
