// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: tests/protos/map.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NestedMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StringAddress map[string]*Address    `protobuf:"bytes,1,rep,name=string_address,json=stringAddress,proto3" json:"string_address,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMap) Reset() {
	*x = NestedMap{}
	mi := &file_tests_protos_map_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMap) ProtoMessage() {}

func (x *NestedMap) ProtoReflect() protoreflect.Message {
	mi := &file_tests_protos_map_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMap.ProtoReflect.Descriptor instead.
func (*NestedMap) Descriptor() ([]byte, []int) {
	return file_tests_protos_map_proto_rawDescGZIP(), []int{0}
}

func (x *NestedMap) GetStringAddress() map[string]*Address {
	if x != nil {
		return x.StringAddress
	}
	return nil
}

type Repeated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repeated) Reset() {
	*x = Repeated{}
	mi := &file_tests_protos_map_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repeated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repeated) ProtoMessage() {}

func (x *Repeated) ProtoReflect() protoreflect.Message {
	mi := &file_tests_protos_map_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repeated.ProtoReflect.Descriptor instead.
func (*Repeated) Descriptor() ([]byte, []int) {
	return file_tests_protos_map_proto_rawDescGZIP(), []int{1}
}

func (x *Repeated) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Map struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Int32Bool       map[int32]bool         `protobuf:"bytes,10,rep,name=int32_bool,json=int32Bool,proto3" json:"int32_bool,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Int64Bool       map[int64]bool         `protobuf:"bytes,11,rep,name=int64_bool,json=int64Bool,proto3" json:"int64_bool,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Uint32Bool      map[uint32]bool        `protobuf:"bytes,12,rep,name=uint32_bool,json=uint32Bool,proto3" json:"uint32_bool,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Uint64Bool      map[uint64]bool        `protobuf:"bytes,13,rep,name=uint64_bool,json=uint64Bool,proto3" json:"uint64_bool,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Sint32Bool      map[int32]bool         `protobuf:"bytes,14,rep,name=sint32_bool,json=sint32Bool,proto3" json:"sint32_bool,omitempty" protobuf_key:"zigzag32,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Sint64Bool      map[int64]bool         `protobuf:"bytes,15,rep,name=sint64_bool,json=sint64Bool,proto3" json:"sint64_bool,omitempty" protobuf_key:"zigzag64,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Fixed32Bool     map[uint32]bool        `protobuf:"bytes,16,rep,name=fixed32_bool,json=fixed32Bool,proto3" json:"fixed32_bool,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Fixed64Bool     map[uint64]bool        `protobuf:"bytes,17,rep,name=fixed64_bool,json=fixed64Bool,proto3" json:"fixed64_bool,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Sfixed32Bool    map[int32]bool         `protobuf:"bytes,18,rep,name=sfixed32_bool,json=sfixed32Bool,proto3" json:"sfixed32_bool,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Sfixed64Bool    map[int64]bool         `protobuf:"bytes,19,rep,name=sfixed64_bool,json=sfixed64Bool,proto3" json:"sfixed64_bool,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringBool      map[string]bool        `protobuf:"bytes,20,rep,name=string_bool,json=stringBool,proto3" json:"string_bool,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringAddress   map[string]*Address    `protobuf:"bytes,21,rep,name=string_address,json=stringAddress,proto3" json:"string_address,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringRepeated  map[string]*Repeated   `protobuf:"bytes,23,rep,name=string_repeated,json=stringRepeated,proto3" json:"string_repeated,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringNestedMap map[string]*NestedMap  `protobuf:"bytes,22,rep,name=string_nested_map,json=stringNestedMap,proto3" json:"string_nested_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Map) Reset() {
	*x = Map{}
	mi := &file_tests_protos_map_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_tests_protos_map_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_tests_protos_map_proto_rawDescGZIP(), []int{2}
}

func (x *Map) GetInt32Bool() map[int32]bool {
	if x != nil {
		return x.Int32Bool
	}
	return nil
}

func (x *Map) GetInt64Bool() map[int64]bool {
	if x != nil {
		return x.Int64Bool
	}
	return nil
}

func (x *Map) GetUint32Bool() map[uint32]bool {
	if x != nil {
		return x.Uint32Bool
	}
	return nil
}

func (x *Map) GetUint64Bool() map[uint64]bool {
	if x != nil {
		return x.Uint64Bool
	}
	return nil
}

func (x *Map) GetSint32Bool() map[int32]bool {
	if x != nil {
		return x.Sint32Bool
	}
	return nil
}

func (x *Map) GetSint64Bool() map[int64]bool {
	if x != nil {
		return x.Sint64Bool
	}
	return nil
}

func (x *Map) GetFixed32Bool() map[uint32]bool {
	if x != nil {
		return x.Fixed32Bool
	}
	return nil
}

func (x *Map) GetFixed64Bool() map[uint64]bool {
	if x != nil {
		return x.Fixed64Bool
	}
	return nil
}

func (x *Map) GetSfixed32Bool() map[int32]bool {
	if x != nil {
		return x.Sfixed32Bool
	}
	return nil
}

func (x *Map) GetSfixed64Bool() map[int64]bool {
	if x != nil {
		return x.Sfixed64Bool
	}
	return nil
}

func (x *Map) GetStringBool() map[string]bool {
	if x != nil {
		return x.StringBool
	}
	return nil
}

func (x *Map) GetStringAddress() map[string]*Address {
	if x != nil {
		return x.StringAddress
	}
	return nil
}

func (x *Map) GetStringRepeated() map[string]*Repeated {
	if x != nil {
		return x.StringRepeated
	}
	return nil
}

func (x *Map) GetStringNestedMap() map[string]*NestedMap {
	if x != nil {
		return x.StringNestedMap
	}
	return nil
}

var File_tests_protos_map_proto protoreflect.FileDescriptor

const file_tests_protos_map_proto_rawDesc = "" +
	"\n" +
	"\x16tests/protos/map.proto\x12\btest.map\x1a\x19tests/protos/common.proto\"\xb2\x01\n" +
	"\tNestedMap\x12M\n" +
	"\x0estring_address\x18\x01 \x03(\v2&.test.map.NestedMap.StringAddressEntryR\rstringAddress\x1aV\n" +
	"\x12StringAddressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.test.common.AddressR\x05value:\x028\x01\">\n" +
	"\bRepeated\x122\n" +
	"\taddresses\x18\x01 \x03(\v2\x14.test.common.AddressR\taddresses\"\xf7\x0e\n" +
	"\x03Map\x12;\n" +
	"\n" +
	"int32_bool\x18\n" +
	" \x03(\v2\x1c.test.map.Map.Int32BoolEntryR\tint32Bool\x12;\n" +
	"\n" +
	"int64_bool\x18\v \x03(\v2\x1c.test.map.Map.Int64BoolEntryR\tint64Bool\x12>\n" +
	"\vuint32_bool\x18\f \x03(\v2\x1d.test.map.Map.Uint32BoolEntryR\n" +
	"uint32Bool\x12>\n" +
	"\vuint64_bool\x18\r \x03(\v2\x1d.test.map.Map.Uint64BoolEntryR\n" +
	"uint64Bool\x12>\n" +
	"\vsint32_bool\x18\x0e \x03(\v2\x1d.test.map.Map.Sint32BoolEntryR\n" +
	"sint32Bool\x12>\n" +
	"\vsint64_bool\x18\x0f \x03(\v2\x1d.test.map.Map.Sint64BoolEntryR\n" +
	"sint64Bool\x12A\n" +
	"\ffixed32_bool\x18\x10 \x03(\v2\x1e.test.map.Map.Fixed32BoolEntryR\vfixed32Bool\x12A\n" +
	"\ffixed64_bool\x18\x11 \x03(\v2\x1e.test.map.Map.Fixed64BoolEntryR\vfixed64Bool\x12D\n" +
	"\rsfixed32_bool\x18\x12 \x03(\v2\x1f.test.map.Map.Sfixed32BoolEntryR\fsfixed32Bool\x12D\n" +
	"\rsfixed64_bool\x18\x13 \x03(\v2\x1f.test.map.Map.Sfixed64BoolEntryR\fsfixed64Bool\x12>\n" +
	"\vstring_bool\x18\x14 \x03(\v2\x1d.test.map.Map.StringBoolEntryR\n" +
	"stringBool\x12G\n" +
	"\x0estring_address\x18\x15 \x03(\v2 .test.map.Map.StringAddressEntryR\rstringAddress\x12J\n" +
	"\x0fstring_repeated\x18\x17 \x03(\v2!.test.map.Map.StringRepeatedEntryR\x0estringRepeated\x12N\n" +
	"\x11string_nested_map\x18\x16 \x03(\v2\".test.map.Map.StringNestedMapEntryR\x0fstringNestedMap\x1a<\n" +
	"\x0eInt32BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a<\n" +
	"\x0eInt64BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a=\n" +
	"\x0fUint32BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a=\n" +
	"\x0fUint64BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a=\n" +
	"\x0fSint32BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x11R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a=\n" +
	"\x0fSint64BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x12R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a>\n" +
	"\x10Fixed32BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\aR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a>\n" +
	"\x10Fixed64BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x06R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a?\n" +
	"\x11Sfixed32BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x0fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a?\n" +
	"\x11Sfixed64BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x10R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a=\n" +
	"\x0fStringBoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1aV\n" +
	"\x12StringAddressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.test.common.AddressR\x05value:\x028\x01\x1aU\n" +
	"\x13StringRepeatedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.test.map.RepeatedR\x05value:\x028\x01\x1aW\n" +
	"\x14StringNestedMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.test.map.NestedMapR\x05value:\x028\x01B Z\vtests/go/pb\xca\x02\x10Tests\\php\\pb\\Mapb\x06proto3"

var (
	file_tests_protos_map_proto_rawDescOnce sync.Once
	file_tests_protos_map_proto_rawDescData []byte
)

func file_tests_protos_map_proto_rawDescGZIP() []byte {
	file_tests_protos_map_proto_rawDescOnce.Do(func() {
		file_tests_protos_map_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_protos_map_proto_rawDesc), len(file_tests_protos_map_proto_rawDesc)))
	})
	return file_tests_protos_map_proto_rawDescData
}

var file_tests_protos_map_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_tests_protos_map_proto_goTypes = []any{
	(*NestedMap)(nil), // 0: test.map.NestedMap
	(*Repeated)(nil),  // 1: test.map.Repeated
	(*Map)(nil),       // 2: test.map.Map
	nil,               // 3: test.map.NestedMap.StringAddressEntry
	nil,               // 4: test.map.Map.Int32BoolEntry
	nil,               // 5: test.map.Map.Int64BoolEntry
	nil,               // 6: test.map.Map.Uint32BoolEntry
	nil,               // 7: test.map.Map.Uint64BoolEntry
	nil,               // 8: test.map.Map.Sint32BoolEntry
	nil,               // 9: test.map.Map.Sint64BoolEntry
	nil,               // 10: test.map.Map.Fixed32BoolEntry
	nil,               // 11: test.map.Map.Fixed64BoolEntry
	nil,               // 12: test.map.Map.Sfixed32BoolEntry
	nil,               // 13: test.map.Map.Sfixed64BoolEntry
	nil,               // 14: test.map.Map.StringBoolEntry
	nil,               // 15: test.map.Map.StringAddressEntry
	nil,               // 16: test.map.Map.StringRepeatedEntry
	nil,               // 17: test.map.Map.StringNestedMapEntry
	(*Address)(nil),   // 18: test.common.Address
}
var file_tests_protos_map_proto_depIdxs = []int32{
	3,  // 0: test.map.NestedMap.string_address:type_name -> test.map.NestedMap.StringAddressEntry
	18, // 1: test.map.Repeated.addresses:type_name -> test.common.Address
	4,  // 2: test.map.Map.int32_bool:type_name -> test.map.Map.Int32BoolEntry
	5,  // 3: test.map.Map.int64_bool:type_name -> test.map.Map.Int64BoolEntry
	6,  // 4: test.map.Map.uint32_bool:type_name -> test.map.Map.Uint32BoolEntry
	7,  // 5: test.map.Map.uint64_bool:type_name -> test.map.Map.Uint64BoolEntry
	8,  // 6: test.map.Map.sint32_bool:type_name -> test.map.Map.Sint32BoolEntry
	9,  // 7: test.map.Map.sint64_bool:type_name -> test.map.Map.Sint64BoolEntry
	10, // 8: test.map.Map.fixed32_bool:type_name -> test.map.Map.Fixed32BoolEntry
	11, // 9: test.map.Map.fixed64_bool:type_name -> test.map.Map.Fixed64BoolEntry
	12, // 10: test.map.Map.sfixed32_bool:type_name -> test.map.Map.Sfixed32BoolEntry
	13, // 11: test.map.Map.sfixed64_bool:type_name -> test.map.Map.Sfixed64BoolEntry
	14, // 12: test.map.Map.string_bool:type_name -> test.map.Map.StringBoolEntry
	15, // 13: test.map.Map.string_address:type_name -> test.map.Map.StringAddressEntry
	16, // 14: test.map.Map.string_repeated:type_name -> test.map.Map.StringRepeatedEntry
	17, // 15: test.map.Map.string_nested_map:type_name -> test.map.Map.StringNestedMapEntry
	18, // 16: test.map.NestedMap.StringAddressEntry.value:type_name -> test.common.Address
	18, // 17: test.map.Map.StringAddressEntry.value:type_name -> test.common.Address
	1,  // 18: test.map.Map.StringRepeatedEntry.value:type_name -> test.map.Repeated
	0,  // 19: test.map.Map.StringNestedMapEntry.value:type_name -> test.map.NestedMap
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_tests_protos_map_proto_init() }
func file_tests_protos_map_proto_init() {
	if File_tests_protos_map_proto != nil {
		return
	}
	file_tests_protos_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_protos_map_proto_rawDesc), len(file_tests_protos_map_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_protos_map_proto_goTypes,
		DependencyIndexes: file_tests_protos_map_proto_depIdxs,
		MessageInfos:      file_tests_protos_map_proto_msgTypes,
	}.Build()
	File_tests_protos_map_proto = out.File
	file_tests_protos_map_proto_goTypes = nil
	file_tests_protos_map_proto_depIdxs = nil
}
