// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: tests/protos/nested.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nested struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *Nested_Data            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	MapData       map[string]*Nested_Data `protobuf:"bytes,3,rep,name=map_data,json=mapData,proto3" json:"map_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RepeatedData  []*Nested_Data          `protobuf:"bytes,4,rep,name=repeated_data,json=repeatedData,proto3" json:"repeated_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_tests_protos_nested_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_tests_protos_nested_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_tests_protos_nested_proto_rawDescGZIP(), []int{0}
}

func (x *Nested) GetData() *Nested_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Nested) GetMapData() map[string]*Nested_Data {
	if x != nil {
		return x.MapData
	}
	return nil
}

func (x *Nested) GetRepeatedData() []*Nested_Data {
	if x != nil {
		return x.RepeatedData
	}
	return nil
}

type Nested_Data struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Value         string                  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	NestedData    *Nested_Data_NestedData `protobuf:"bytes,2,opt,name=nested_data,json=nestedData,proto3" json:"nested_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested_Data) Reset() {
	*x = Nested_Data{}
	mi := &file_tests_protos_nested_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested_Data) ProtoMessage() {}

func (x *Nested_Data) ProtoReflect() protoreflect.Message {
	mi := &file_tests_protos_nested_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested_Data.ProtoReflect.Descriptor instead.
func (*Nested_Data) Descriptor() ([]byte, []int) {
	return file_tests_protos_nested_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Nested_Data) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Nested_Data) GetNestedData() *Nested_Data_NestedData {
	if x != nil {
		return x.NestedData
	}
	return nil
}

type Nested_Data_NestedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested_Data_NestedData) Reset() {
	*x = Nested_Data_NestedData{}
	mi := &file_tests_protos_nested_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested_Data_NestedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested_Data_NestedData) ProtoMessage() {}

func (x *Nested_Data_NestedData) ProtoReflect() protoreflect.Message {
	mi := &file_tests_protos_nested_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested_Data_NestedData.ProtoReflect.Descriptor instead.
func (*Nested_Data_NestedData) Descriptor() ([]byte, []int) {
	return file_tests_protos_nested_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Nested_Data_NestedData) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_tests_protos_nested_proto protoreflect.FileDescriptor

const file_tests_protos_nested_proto_rawDesc = "" +
	"\n" +
	"\x19tests/protos/nested.proto\x12\vtest.nested\"\x91\x03\n" +
	"\x06Nested\x12,\n" +
	"\x04data\x18\x02 \x01(\v2\x18.test.nested.Nested.DataR\x04data\x12;\n" +
	"\bmap_data\x18\x03 \x03(\v2 .test.nested.Nested.MapDataEntryR\amapData\x12=\n" +
	"\rrepeated_data\x18\x04 \x03(\v2\x18.test.nested.Nested.DataR\frepeatedData\x1a\x86\x01\n" +
	"\x04Data\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12D\n" +
	"\vnested_data\x18\x02 \x01(\v2#.test.nested.Nested.Data.NestedDataR\n" +
	"nestedData\x1a\"\n" +
	"\n" +
	"NestedData\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x1aT\n" +
	"\fMapDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.test.nested.Nested.DataR\x05value:\x028\x01B#Z\vtests/go/pb\xca\x02\x13Tests\\php\\pb\\Nestedb\x06proto3"

var (
	file_tests_protos_nested_proto_rawDescOnce sync.Once
	file_tests_protos_nested_proto_rawDescData []byte
)

func file_tests_protos_nested_proto_rawDescGZIP() []byte {
	file_tests_protos_nested_proto_rawDescOnce.Do(func() {
		file_tests_protos_nested_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_protos_nested_proto_rawDesc), len(file_tests_protos_nested_proto_rawDesc)))
	})
	return file_tests_protos_nested_proto_rawDescData
}

var file_tests_protos_nested_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tests_protos_nested_proto_goTypes = []any{
	(*Nested)(nil),                 // 0: test.nested.Nested
	(*Nested_Data)(nil),            // 1: test.nested.Nested.Data
	nil,                            // 2: test.nested.Nested.MapDataEntry
	(*Nested_Data_NestedData)(nil), // 3: test.nested.Nested.Data.NestedData
}
var file_tests_protos_nested_proto_depIdxs = []int32{
	1, // 0: test.nested.Nested.data:type_name -> test.nested.Nested.Data
	2, // 1: test.nested.Nested.map_data:type_name -> test.nested.Nested.MapDataEntry
	1, // 2: test.nested.Nested.repeated_data:type_name -> test.nested.Nested.Data
	3, // 3: test.nested.Nested.Data.nested_data:type_name -> test.nested.Nested.Data.NestedData
	1, // 4: test.nested.Nested.MapDataEntry.value:type_name -> test.nested.Nested.Data
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tests_protos_nested_proto_init() }
func file_tests_protos_nested_proto_init() {
	if File_tests_protos_nested_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_protos_nested_proto_rawDesc), len(file_tests_protos_nested_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_protos_nested_proto_goTypes,
		DependencyIndexes: file_tests_protos_nested_proto_depIdxs,
		MessageInfos:      file_tests_protos_nested_proto_msgTypes,
	}.Build()
	File_tests_protos_nested_proto = out.File
	file_tests_protos_nested_proto_goTypes = nil
	file_tests_protos_nested_proto_depIdxs = nil
}
