// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: repeated.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Emails        []string               `protobuf:"bytes,2,rep,name=emails,proto3" json:"emails,omitempty"`
	Ages          []int32                `protobuf:"varint,3,rep,packed,name=ages,proto3" json:"ages,omitempty"`
	IsAdmin       []bool                 `protobuf:"varint,4,rep,packed,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_repeated_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_repeated_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_repeated_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Organization) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *Organization) GetAges() []int32 {
	if x != nil {
		return x.Ages
	}
	return nil
}

func (x *Organization) GetIsAdmin() []bool {
	if x != nil {
		return x.IsAdmin
	}
	return nil
}

var File_repeated_proto protoreflect.FileDescriptor

const file_repeated_proto_rawDesc = "" +
	"\n" +
	"\x0erepeated.proto\x12\rtest.repeated\x1a\rimports.proto\"\x7f\n" +
	"\fOrganization\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.test.imports.UserR\x05users\x12\x16\n" +
	"\x06emails\x18\x02 \x03(\tR\x06emails\x12\x12\n" +
	"\x04ages\x18\x03 \x03(\x05R\x04ages\x12\x19\n" +
	"\bis_admin\x18\x04 \x03(\bR\aisAdminB\x17Z\n" +
	"proteus/pb\xca\x02\bTests\\PBb\x06proto3"

var (
	file_repeated_proto_rawDescOnce sync.Once
	file_repeated_proto_rawDescData []byte
)

func file_repeated_proto_rawDescGZIP() []byte {
	file_repeated_proto_rawDescOnce.Do(func() {
		file_repeated_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repeated_proto_rawDesc), len(file_repeated_proto_rawDesc)))
	})
	return file_repeated_proto_rawDescData
}

var file_repeated_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_repeated_proto_goTypes = []any{
	(*Organization)(nil), // 0: test.repeated.Organization
	(*User)(nil),         // 1: test.imports.User
}
var file_repeated_proto_depIdxs = []int32{
	1, // 0: test.repeated.Organization.users:type_name -> test.imports.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_repeated_proto_init() }
func file_repeated_proto_init() {
	if File_repeated_proto != nil {
		return
	}
	file_imports_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repeated_proto_rawDesc), len(file_repeated_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repeated_proto_goTypes,
		DependencyIndexes: file_repeated_proto_depIdxs,
		MessageInfos:      file_repeated_proto_msgTypes,
	}.Build()
	File_repeated_proto = out.File
	file_repeated_proto_goTypes = nil
	file_repeated_proto_depIdxs = nil
}
