// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: tests/protos/scalars.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// see https://protobuf.dev/programming-guides/proto3/#scalar
type Scalars struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uses IEEE 754 double-precision format.
	Double float64 `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	// Uses variable-length encoding. Inefficient for encoding negative numbers - if your field is likely to have negative values, use sint32 instead.
	Int32 int32 `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	// Uses variable-length encoding. Inefficient for encoding negative numbers - if your field is likely to have negative values, use sint64 instead.
	Int64 int64 `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
	// Uses variable-length encoding.
	Uint32 uint32 `protobuf:"varint,5,opt,name=uint32,proto3" json:"uint32,omitempty"`
	// Uses variable-length encoding.
	Uint64 uint64 `protobuf:"varint,6,opt,name=uint64,proto3" json:"uint64,omitempty"`
	// Uses variable-length encoding. Signed int value. These more efficiently encode negative numbers than regular int32s.
	Sint32 int32 `protobuf:"zigzag32,7,opt,name=sint32,proto3" json:"sint32,omitempty"`
	// Uses variable-length encoding. Signed int value. These more efficiently encode negative numbers than regular int64s.
	Sint64 int64 `protobuf:"zigzag64,8,opt,name=sint64,proto3" json:"sint64,omitempty"`
	// Always four bytes. More efficient than uint32 if values are often greater than 228.
	Fixed32 uint32 `protobuf:"fixed32,9,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	// Always eight bytes. More efficient than uint64 if values are often greater than 256.
	Fixed64 uint64 `protobuf:"fixed64,10,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	// Always four bytes.
	Sfixed32 int32 `protobuf:"fixed32,11,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	// Always eight bytes.
	Sfixed64 int64 `protobuf:"fixed64,12,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Bool     bool  `protobuf:"varint,13,opt,name=bool,proto3" json:"bool,omitempty"`
	// A string must always contain UTF-8 encoded or 7-bit ASCII text, and cannot be longer than 232.
	String_ string `protobuf:"bytes,14,opt,name=string,proto3" json:"string,omitempty"`
	// May contain any arbitrary sequence of bytes no longer than 232.
	Bytes         []byte `protobuf:"bytes,15,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scalars) Reset() {
	*x = Scalars{}
	mi := &file_tests_protos_scalars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scalars) ProtoMessage() {}

func (x *Scalars) ProtoReflect() protoreflect.Message {
	mi := &file_tests_protos_scalars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scalars.ProtoReflect.Descriptor instead.
func (*Scalars) Descriptor() ([]byte, []int) {
	return file_tests_protos_scalars_proto_rawDescGZIP(), []int{0}
}

func (x *Scalars) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *Scalars) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *Scalars) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *Scalars) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *Scalars) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *Scalars) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *Scalars) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *Scalars) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *Scalars) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *Scalars) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *Scalars) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *Scalars) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Scalars) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *Scalars) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

var File_tests_protos_scalars_proto protoreflect.FileDescriptor

const file_tests_protos_scalars_proto_rawDesc = "" +
	"\n" +
	"\x1atests/protos/scalars.proto\x12\ftest.scalars\"\xdb\x02\n" +
	"\aScalars\x12\x16\n" +
	"\x06double\x18\x01 \x01(\x01R\x06double\x12\x14\n" +
	"\x05int32\x18\x03 \x01(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\x04 \x01(\x03R\x05int64\x12\x16\n" +
	"\x06uint32\x18\x05 \x01(\rR\x06uint32\x12\x16\n" +
	"\x06uint64\x18\x06 \x01(\x04R\x06uint64\x12\x16\n" +
	"\x06sint32\x18\a \x01(\x11R\x06sint32\x12\x16\n" +
	"\x06sint64\x18\b \x01(\x12R\x06sint64\x12\x18\n" +
	"\afixed32\x18\t \x01(\aR\afixed32\x12\x18\n" +
	"\afixed64\x18\n" +
	" \x01(\x06R\afixed64\x12\x1a\n" +
	"\bsfixed32\x18\v \x01(\x0fR\bsfixed32\x12\x1a\n" +
	"\bsfixed64\x18\f \x01(\x10R\bsfixed64\x12\x12\n" +
	"\x04bool\x18\r \x01(\bR\x04bool\x12\x16\n" +
	"\x06string\x18\x0e \x01(\tR\x06string\x12\x14\n" +
	"\x05bytes\x18\x0f \x01(\fR\x05bytesB$Z\vtests/go/pb\xca\x02\x14Tests\\php\\pb\\Scalarsb\x06proto3"

var (
	file_tests_protos_scalars_proto_rawDescOnce sync.Once
	file_tests_protos_scalars_proto_rawDescData []byte
)

func file_tests_protos_scalars_proto_rawDescGZIP() []byte {
	file_tests_protos_scalars_proto_rawDescOnce.Do(func() {
		file_tests_protos_scalars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_protos_scalars_proto_rawDesc), len(file_tests_protos_scalars_proto_rawDesc)))
	})
	return file_tests_protos_scalars_proto_rawDescData
}

var file_tests_protos_scalars_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_protos_scalars_proto_goTypes = []any{
	(*Scalars)(nil), // 0: test.scalars.Scalars
}
var file_tests_protos_scalars_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_protos_scalars_proto_init() }
func file_tests_protos_scalars_proto_init() {
	if File_tests_protos_scalars_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_protos_scalars_proto_rawDesc), len(file_tests_protos_scalars_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_protos_scalars_proto_goTypes,
		DependencyIndexes: file_tests_protos_scalars_proto_depIdxs,
		MessageInfos:      file_tests_protos_scalars_proto_msgTypes,
	}.Build()
	File_tests_protos_scalars_proto = out.File
	file_tests_protos_scalars_proto_goTypes = nil
	file_tests_protos_scalars_proto_depIdxs = nil
}
