<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/test.proto

namespace Tests\GoogleProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>test.DataTypes</code>
 */
class DataTypes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string str_test = 1 [json_name = "strTest"];</code>
     */
    protected $str_test = '';
    /**
     * Generated from protobuf field <code>int32 int_test = 2 [json_name = "intTest"];</code>
     */
    protected $int_test = 0;
    /**
     * Generated from protobuf field <code>bool bool_test = 3 [json_name = "boolTest"];</code>
     */
    protected $bool_test = false;
    /**
     * Generated from protobuf field <code>float float_test = 4 [json_name = "floatTest"];</code>
     */
    protected $float_test = 0.0;
    /**
     * Generated from protobuf field <code>double double_test = 5 [json_name = "doubleTest"];</code>
     */
    protected $double_test = 0.0;
    /**
     * Generated from protobuf field <code>bytes bytes_test = 6 [json_name = "bytesTest"];</code>
     */
    protected $bytes_test = '';
    /**
     * Generated from protobuf field <code>map<string, string> map_test = 7 [json_name = "mapTest"];</code>
     */
    private $map_test;
    /**
     * Generated from protobuf field <code>repeated int32 int_test_list = 8 [json_name = "intTestList"];</code>
     */
    private $int_test_list;
    /**
     * Generated from protobuf field <code>uint64 uint64_test = 9 [json_name = "uint64Test"];</code>
     */
    protected $uint64_test = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $str_test
     *     @type int $int_test
     *     @type bool $bool_test
     *     @type float $float_test
     *     @type float $double_test
     *     @type string $bytes_test
     *     @type array|\Google\Protobuf\Internal\MapField $map_test
     *     @type int[] $int_test_list
     *     @type int|string $uint64_test
     * }
     */
    public function __construct($data = NULL) {
        \Tests\GoogleProto\Test::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string str_test = 1 [json_name = "strTest"];</code>
     * @return string
     */
    public function getStrTest()
    {
        return $this->str_test;
    }

    /**
     * Generated from protobuf field <code>string str_test = 1 [json_name = "strTest"];</code>
     * @param string $var
     * @return $this
     */
    public function setStrTest($var)
    {
        GPBUtil::checkString($var, True);
        $this->str_test = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 int_test = 2 [json_name = "intTest"];</code>
     * @return int
     */
    public function getIntTest()
    {
        return $this->int_test;
    }

    /**
     * Generated from protobuf field <code>int32 int_test = 2 [json_name = "intTest"];</code>
     * @param int $var
     * @return $this
     */
    public function setIntTest($var)
    {
        GPBUtil::checkInt32($var);
        $this->int_test = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool_test = 3 [json_name = "boolTest"];</code>
     * @return bool
     */
    public function getBoolTest()
    {
        return $this->bool_test;
    }

    /**
     * Generated from protobuf field <code>bool bool_test = 3 [json_name = "boolTest"];</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolTest($var)
    {
        GPBUtil::checkBool($var);
        $this->bool_test = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float float_test = 4 [json_name = "floatTest"];</code>
     * @return float
     */
    public function getFloatTest()
    {
        return $this->float_test;
    }

    /**
     * Generated from protobuf field <code>float float_test = 4 [json_name = "floatTest"];</code>
     * @param float $var
     * @return $this
     */
    public function setFloatTest($var)
    {
        GPBUtil::checkFloat($var);
        $this->float_test = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_test = 5 [json_name = "doubleTest"];</code>
     * @return float
     */
    public function getDoubleTest()
    {
        return $this->double_test;
    }

    /**
     * Generated from protobuf field <code>double double_test = 5 [json_name = "doubleTest"];</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleTest($var)
    {
        GPBUtil::checkDouble($var);
        $this->double_test = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bytes_test = 6 [json_name = "bytesTest"];</code>
     * @return string
     */
    public function getBytesTest()
    {
        return $this->bytes_test;
    }

    /**
     * Generated from protobuf field <code>bytes bytes_test = 6 [json_name = "bytesTest"];</code>
     * @param string $var
     * @return $this
     */
    public function setBytesTest($var)
    {
        GPBUtil::checkString($var, False);
        $this->bytes_test = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> map_test = 7 [json_name = "mapTest"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMapTest()
    {
        return $this->map_test;
    }

    /**
     * Generated from protobuf field <code>map<string, string> map_test = 7 [json_name = "mapTest"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMapTest($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->map_test = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 int_test_list = 8 [json_name = "intTestList"];</code>
     * @return RepeatedField<int>
     */
    public function getIntTestList()
    {
        return $this->int_test_list;
    }

    /**
     * Generated from protobuf field <code>repeated int32 int_test_list = 8 [json_name = "intTestList"];</code>
     * @param int[] $var
     * @return $this
     */
    public function setIntTestList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->int_test_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 uint64_test = 9 [json_name = "uint64Test"];</code>
     * @return int|string
     */
    public function getUint64Test()
    {
        return $this->uint64_test;
    }

    /**
     * Generated from protobuf field <code>uint64 uint64_test = 9 [json_name = "uint64Test"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setUint64Test($var)
    {
        GPBUtil::checkUint64($var);
        $this->uint64_test = $var;

        return $this;
    }

}

