<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/test.proto

namespace Tests\GoogleProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>test.DelayRequest</code>
 */
class DelayRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ms = 1 [json_name = "ms"];</code>
     */
    protected $ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ms
     * }
     */
    public function __construct($data = NULL) {
        \Tests\GoogleProto\Test::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 ms = 1 [json_name = "ms"];</code>
     * @return int
     */
    public function getMs()
    {
        return $this->ms;
    }

    /**
     * Generated from protobuf field <code>int32 ms = 1 [json_name = "ms"];</code>
     * @param int $var
     * @return $this
     */
    public function setMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->ms = $var;

        return $this;
    }

}

