<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/test.proto

namespace Tests\GoogleProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>test.FailurePatternRequest</code>
 */
class FailurePatternRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 fail_times = 1 [json_name = "failTimes"];</code>
     */
    protected $fail_times = 0;
    /**
     * Generated from protobuf field <code>int32 error_code = 2 [json_name = "errorCode"];</code>
     */
    protected $error_code = 0;
    /**
     * Generated from protobuf field <code>string key = 3 [json_name = "key"];</code>
     */
    protected $key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $fail_times
     *     @type int $error_code
     *     @type string $key
     * }
     */
    public function __construct($data = NULL) {
        \Tests\GoogleProto\Test::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 fail_times = 1 [json_name = "failTimes"];</code>
     * @return int
     */
    public function getFailTimes()
    {
        return $this->fail_times;
    }

    /**
     * Generated from protobuf field <code>int32 fail_times = 1 [json_name = "failTimes"];</code>
     * @param int $var
     * @return $this
     */
    public function setFailTimes($var)
    {
        GPBUtil::checkInt32($var);
        $this->fail_times = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 error_code = 2 [json_name = "errorCode"];</code>
     * @return int
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * Generated from protobuf field <code>int32 error_code = 2 [json_name = "errorCode"];</code>
     * @param int $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->error_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key = 3 [json_name = "key"];</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 3 [json_name = "key"];</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

}

